// src/components/products/products.data.js

export const HIGHLIGHT_COLOR = "oklch(50.8% 0.118 165.612)";

export const PRODUCTS = {
  Oilseeds: {
    color: HIGHLIGHT_COLOR,
    countries: {
      "United States of America": ["Soybean"],
      Brazil: ["Soybean"],
      Argentina: ["Soybean", "Sunflower"],
      Canada: ["Canola"],
      Ukraine: ["Soybean", "Sunflower", "Rapeseed"],
      Russia: ["Soybean", "Sunflower", "Rapeseed"],
      India: ["Soybean", "Rapeseed", "Groundnut", "Sesame"],
      Australia: ["Canola"],
      Benin: ["Soybean", "Cottonseed"],
      Togo: ["Soybean"],
      "Burkina Faso": ["Soybean"],
      Myanmar: ["Soybean"],
      Ethiopia: ["Soybean"],
      Tanzania: ["Soybean", "Sesame"],
      Mozambique: ["Soybean"],
      Nigeria: ["Soybean", "Sesame"],
      Philippines: ["Coconut"],
      Paraguay: ["Soybean"],
    },
    index: [
      "Soybean",
      "Canola",
      "Rapeseed",
      "Groundnut",
      "Sesame",
      "Cottonseed",
      "Coconut",
    ],
  },

  Pulses: {
    color: HIGHLIGHT_COLOR,
    countries: {
      India: ["Lentils", "Chickpeas", "Pigeon Peas", "Black Matpe", "Kidney Beans"],
      Canada: ["Faba Beans", "Chickpeas", "Lentils", "Yellow Peas"],
      Australia: ["Faba Beans", "Chickpeas", "Yellow Peas", "Lentils"],
      Myanmar: ["Black Matpe", "Pigeon Peas"],
      Russia: ["Lentils", "Chickpeas", "Yellow Peas"],
      Ethiopia: ["Kidney Beans", "Pigeon Peas", "Chickpeas", "Lentils"],
      Uganda: ["Kidney Beans"],
      Tanzania: ["Chickpeas", "Pigeon Peas"],
      Mozambique: ["Pigeon Peas"],
      Malawi: ["Pigeon Peas"],
      Nigeria: ["Pigeon Peas"],
      Sudan: ["Chickpeas", "Pigeon Peas"],
      Kenya: ["Pigeon Peas"],
      Ukraine: ["Chickpeas", "Peas", "Yellow Peas"],
      Turkey: ["Chickpeas", "Yellow Peas"],
      Brazil: ["Kidney Beans", "Black Matpe"],
      Argentina: ["Kidney Beans", "Chickpeas", "Yellow Peas"],
      Egypt: ["Kidney Beans"],
      Lithuania: ["Yellow Peas"],
      Latvia: ["Yellow Peas"],
      Estonia: ["Yellow Peas"],
      Belarus: ["Yellow Peas"],
    },
    index: [
      "Lentils",
      "Chickpeas",
      "Yellow Peas",
      "Pigeon Peas",
      "Black Matpe",
      "Kidney Beans",
      "Faba Beans",
    ],
  },

  Grains: {
    color: HIGHLIGHT_COLOR,
    countries: {
      India: ["Wheat", "Rice", "Maize", "Sorghum"],
      Myanmar: ["Maize"],
      China: ["Maize"],
      Vietnam: ["Rice"],
      Thailand: ["Rice"],
      "United States of America": ["Maize", "Wheat", "Sorghum"],
      Ukraine: ["Maize", "Barley", "Sorghum"],
      Russia: ["Wheat", "Barley"],
      Argentina: ["Maize", "Wheat", "Sorghum"],
      Australia: ["Oats", "Wheat", "Barley", "Sorghum"],
      France: ["Barley"],
      Canada: ["Oats"],
    },
    index: ["Wheat", "Rice", "Maize", "Barley", "Sorghum", "Oats"],
  },
};
